blog/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
urlpatterns = [
    url(r'^index/$', views.index, name = "index"),
    url(r'^article/(?P<article_id>\d+)$', views.article_page, name = 'article_page'),
    url(r'^archive/$', views.archive, name = 'archive'),
    url(r'^tag/(?P<tag_name>\w+)$', views.search_tag, name = "search_tag"),
    url(r'^aboutme/$', views.about_me, name = "about_me"),
    url(r'^search/$', views.search_str, name = "search"),
    url(r'^feed/$', views.RSSFeed(), name = "RSS"),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from api_note.views import NotebookViewSet, NoteViewSet, TagViewSet, AlbumViewSet, ImageViewSet
from user_group.views import UserViewSet, GroupViewSet

api_router = DefaultRouter()
api_router.register(r'tag', TagViewSet)
api_router.register(r'notebook', NotebookViewSet)
api_router.register(r'user', UserViewSet)
api_router.register(r'group', GroupViewSet)
api_router.register(r'note', NoteViewSet)
api_router.register(r'album', AlbumViewSet)
api_router.register(r'image', ImageViewSet)



schema_view = get_schema_view(title='Pastebin API')
urlpatterns = [
    url(r'^api/', include(api_router.urls)),
    url(r'^note/', include('note.urls', namespace='note')),
    url(r'^schema/$', schema_view),
    url(r'blog/', include('blog.urls', namespace = 'blog')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=50, blank=True)
    pub_time = models.DateTimeField(auto_now_add=True)
    content = models.TextField(blank = True, null = True)

    def get_absolute_url(self):
        return "http://127.0.0.1:8000/blog/article/%s" % self.id

    def __unicode__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from api_note.models import Note
from django.http import Http404
from django.contrib.syndication.views import Feed
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# class RSSFeed(Feed) :
#     title = "RSS feed - article"
#     link = "feeds/posts/"
#     description = "RSS feed - blog posts"
#
#     def items(self):
#         return Article.objects.order_by('-pub_time')
#
#     def item_title(self, item):
#         return item.title
#
#     def item_pubdate(self, item):
#         return item.pub_time
#
#     def item_description(self, item):
#         return item.content

# Create your views here.
# {% if $.curIsIndex %}
#     {% $.blogInfo.Title % %} }
# {% else if $.curIsCate %}
#     分类-{% $.curCateTitle %}
# {% else if $.curIsSearch %}
#     搜索-{% $.keywords %}
# {% else if $.curIsTags %}
#     我的标签
# {% else if $.curIsTagPosts %}
#     标签-{% $.curTag %}
# {% else if $.curIsPost %}
# 	{% $.post.Title %}
# {% else if $.curIsSingle %}
# 	{% $.single.Title %}
# {% else if $.curIsArchive %}
# 	归档
# {% endif %}

def index(request):
    notes = Note.objects.filter(IsBlog=True).order_by('UpdatedTime')
    paginator = Paginator(notes, 10)
    page = request.GET.get('page')
    hf = object()
    user_info = object()
    hf.curIsIndex = True
    hf.blogInfo.Title = "I am title"
    # header.curIsPost = False
    # header.curIsSingle = False
    user_info.Username = "I am username"
    hf.indexUrl = "http://127.0.0.1:8000/2997215859"
    hf.blogInfo.Logo = True
    hf.blogInfo.Logo = "http://leanote.com/public/upload/712/57cccf2aab644133ed0714c2/images/logo/a8797f65fa1ffd93d83dfefee572b898.jpg"
    hf.blogInfo.Title = "但愿常醉不愿醒 的 博客"
    hf.blogInfo.SubTitle = "Stay hungry, stay foolish!"
    index_url = "http://blog.leanote.com/2997215859"

    hf.singles = []
    hf.singleUrl = "http://blog.leanote.com/single/2997215859/"
    hf.curSingleId = ""
    about_me = object()
    about_me.UrlTitle = "About-Me"
    about_me.Title = "About Me"
    hf.singles.append(about_me)

    hf.curIsArchive = False
    hf.archiveUrl = "http://blog.leanote.com/archives/2997215859"

    hf.curIsTags = False
    hf.tagsUrl = "http://blog.leanote.com/tags/2997215859"

    keywords = ""


    try:
        current_articles = paginator.page(page)
    except PageNotAnInteger:
        current_articles = paginator.page(1)
    except EmptyPage:
        current_articles = paginator.page(paginator.num_pages)

    for current_article in current_articles:
        current_article.tags = current_article.category.split(",")
    return render(request, 'blog/index2.html', {
        'articles': current_articles,
        'hf': hf,
        'userInfo': user_info,
        'indexUrl': index_url,
        'keywords': keywords
    })

# def index(request):
#     articles = Note.objects.all()
#     paginator = Paginator(articles, 200)
#     page = request.GET.get('page')
#     try:
#         current_articles = paginator.page(page)
#     except PageNotAnInteger:
#         current_articles = paginator.page(1)
#     except EmptyPage:
#         current_articles = paginator.page(paginator.num_pages)
#
#     for current_article in current_articles:
#         current_article.tags = current_article.category.split(",")
#     return render(request, 'blog/index.html', {'articles': current_articles})

# def article_page(request, article_id):
#     try:
#         article = Article.objects.get(id=str(article_id))
#     except Article.DoesNotExist:
#         raise Http404
#     return render(request, 'blog/article_page.html', {'article': article})
#
# def archive(request):
#     try:
#         articles = Article.objects.all()
#     except Article.DoesNotExist:
#         raise Http404
#     return render(request, 'blog/archive.html', {'articles': articles})
#
# def search_tag(request, tag_name):
#     try:
#         articles = Article.objects.filter(category=tag_name)
#     except Article.DoesNotExist:
#         raise Http404
#     return render(request, 'blog/tag.html', {'articles': articles, 'error': False})
#
# def about_me(request):
#     return render(request, 'blog/about_me.html')
#
# def search_str(request):
#     is_find = False
#     if 'search_str' in request.POST:
#         search_str = request.POST['search_str']
#         if not search_str:
#             return render(request, 'blog/index.html')
#         else:
#             articles = Article.objects.filter(title__icontains=search_str)
#             if len(articles) != 0:
#                 is_find = True
#         return render(request, 'blog/search.html', {'articles': articles})
#
#     return render(request, 'blog/index.html')

blog/templates/blog/about_me.html
{% extends "blog/base.html" %}
{% load custom_markdown %}

{% block content %}
<div class="posts">
        <p> About Me 正在建设中 </p>
</div><!-- /.blog-post -->
{% endblock %}

blog/templates/blog/archive.html
{% extends "blog/base.html" %}

{% block content %}
<div class="posts">
    {% for article in articles %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url "blog:article_page" article_id=article.id %}">{{ article.title }}</a></h2>
                <p class="post-meta">
                    Time:  <a class="post-author" href="#">{{ article.pub_time |date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="{% url "search_tag" tag=article.category %}">{{ article.category }}</a>
                </p>
            </header>
        </section>
    {% endfor %}
</div><!-- /.blog-post -->
{% endblock %}

blog/templates/blog/article_page.html
{% extends "blog/base.html" %}
{% load custom_markdown %}
{% block content %}
<div class="posts">
    <section class="post">
        <header class="post-header">
            <h2 class="post-title">{{ article.title }}</h2>

                <p class="post-meta">
                    Time:  <a class="post-author" href="#">{{ article.pub_time|date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="#">{{ article.category }}</a>
                </p>
        </header>
        <div class="post-description">
            <p>
                {{ article.content | custom_markdown}}
            </p>
        </div>
    </section>
    {% include "blog/duoshuo.html" %}
</div><!-- /.blog-post -->
{% endblock %}

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A layout example that shows off a blog page with a list of posts.">

    <title>Ruiy 's Blog</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/font-awesome.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}">
</head>
<body style="zoom: 1">
<div id="headerAndNav" >
	<div id="headerContainer" class="container">

		<div id="header">


			<h1>
				<a href="http://blog.leanote.com/2997215859" id="logo">

    				<div class="blog-logo">
    				    <img src="http://leanote.com/public/upload/712/57cccf2aab644133ed0714c2/images/logo/a8797f65fa1ffd93d83dfefee572b898.jpg" title="但愿常醉不愿醒 的 博客"/>
    				</div>

    				<div>
    				    但愿常醉不愿醒 的 博客
    				</div>
				</a>
			</h1>
			<div id="blogDesc">
				Love Leanote!
			</div>
		</div>
	</div>


	<div class="navbar navbar-default">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="http://blog.leanote.com/2997215859">

			    <img src="http://leanote.com/public/upload/712/57cccf2aab644133ed0714c2/images/logo/a8797f65fa1ffd93d83dfefee572b898.jpg" title="但愿常醉不愿醒 的 博客"/>

			但愿常醉不愿醒 的 博客

	      </a>
	    </div>
	    <div class="navbar-collapse collapse">
	      <ul class="nav navbar-nav">

	    	<li class="active"><a href="{% url "blog:index" %}">主页</a></li>
			    <li class="">
					<a href="http://blog.leanote.com/single/2997215859/About-Me">About Me</a>
				</li>



			<li class="">
				<a href="http://blog.leanote.com/archives/2997215859">归档</a>
			</li>
			<li class="">
				<a href="http://blog.leanote.com/tags/2997215859">标签</a>
			</li>

	      </ul>
	      <form class="navbar-form navbar-right" id="search" onsubmit="search(event);return false;">
	      	<div class="input-group">
			  	<span class="input-group-addon" id="searchIcon" onclick="search(event);"><i class="fa fa-search"></i></span>
		        <input type="text" placeholder="search" id="searchInput" class="form-control" value="">
		  	</div>
	      </form>
	    </div>
	  </div>
	</div>
</div>

<div id="postsContainer">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>

blog/templates/blog/duoshuo.html
<!-- 多说评论框 start -->
<div class="ds-thread" data-thread-key="{{ article.id }}" data-title="{{ article.title }}" data-url="{{ article.get_absolute_url }}"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"ruiy"};
(function() {
    var ds = document.createElement('script');
    ds.type = 'text/javascript';ds.async = true;
    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
    ds.charset = 'UTF-8';
    (document.getElementsByTagName('head')[0]
     || document.getElementsByTagName('body')[0]).appendChild(ds);
})();
</script>
<!-- 多说公共JS代码 end -->

blog/templates/blog/footer.html
<div id="footerContainer">
	{% userId := hf.blogInfo.UserId %}
	<div class="container" id="footer">
        <div class="col-md-4">
          <h3>导航</h3>
          <ul>
          	<li><a href="{{ hf.indexUrl }}">主页</a></li>
          	{% for cate in hf.cates %}
			<li>
				<a href="{{ hf.cateUrl }}/{{ cate.UrlTitle }}">{{ cate.Title }}</a>
			</li>
			{%  endfor  %}
			<!-- 单页 -->
			{% for single in hf.singles %}
			    <li class="{%  ifequal hf.curSingleId cate.SingleId %}active{%  endifequal  %}">
					<a href="{{ hf.singleUrl }}/ {{ cate.UrlTitle }}">{{ cate.Title }}</a>
				</li>
			{% endfor %}

			<!-- 归档 -->
			<li class="{% if hf.curIsArchive  %}active{%  endif  %}">
				<a href="{{  hf.archiveUrl }}">归档</a>
			</li>
			<li class="{% if hf.curIsTags %}active{% endif %}">
				<a href="{{ hf.tagsUrl }}">标签</a>
			</li>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>最近发表</h3>
          <ul>
          	{% for post in recentPosts %}
          	<li title="{{ post.Title }}"><a href="{{ hf.postUrl }}/{{ post.UrlTitle }}">{{ post.Title }}</a></li>
          	{% endfor %}
          </ul>
       </div>
        <div class="col-md-4">
          <h3>友情链接 </h3>
          <ul>
          	{% if hf.themeInfo.FriendLinks %}
          		{% for link in hf.themeInfo.FriendLinks %}
					<li><a href="{{ link.Url }}" target="_blank">{{ post.Title }}</a></li>
          		{% endfor %}
          	{% endif %}
		 </ul>
        </div>
    </div>
    <div class="footer-leanote">Proudly powered by <a href="https://leanote.com">Leanote</a></div>
</div>
<script src="{{ hf.jQueryUrl }}"></script>
<script src="{{ hf.bootstrapJsUrl }}"></script>
<script src="{{ hf.siteUrl }}/js/bootstrap-hover-dropdown.js"></script>
<script>
// 搜索
function search(e) {
	var keywords = hf("#searchInput").val();
	if(!keywords) {
		location.href = "{{ hf.searchUrl }}";
	} else {
		var tpl = '<form action="{{ hf.searchUrl }}" method="get">';
		tpl += '<input name="keywords" value="' + keywords + '" />';
		tpl += "</form";
		hf(tpl).submit();
	}
}
</script>

blog/templates/blog/header.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="leanote,leanote.com">
<meta name="description" content="leanote, not only a notebook">
<meta name="author" content="leanote">

<title>
{% if header.curIsIndex %}
    {% header.blogInfo.Title %}
{% else if header.curIsCate %}
    分类-{% header.curCateTitle %}
{% else if header.curIsSearch %}
    搜索-{% header.keywords %}
{% else if header.curIsTags %}
    我的标签
{% else if header.curIsTagPosts %}
    标签-{% header.curTag %}
{% else if header.curIsPost %}
	{% header.post.Title %}
{% else if header.curIsSingle %}
	{% header.single.Title %}
{% else if header.curIsArchive %}
	归档
{% endif %}

</title>
<!-- Bootstrap core CSS -->
{% load staticfiles %}
<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
<!-- 字体必须同一域 -->
<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
<link href="{% static "blog/css/style.css" %}/style.css" rel="stylesheet">
<script>
function log(o) {
}
</script>
<style>

</style>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?63adf4c3e1d84ebedd2d9f1e483904eb";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>

</head>
<body>

{% if header.curIsPost or header.curIsSingle %}
<div class="clearfix">
{% endif if %}
<div id="headerAndNav" >
	<div id="headerContainer" class="container">
		<!-- 头部可放博客名, 导航 -->
		<div id="header">

			{{ userInfo.Username }}
			<h1>
				<a href="{{ hf.indexUrl }}" id="logo">
    				{% if hf.blogInfo.Logo %}
    				<div class="blog-logo">
    				    <img src="{{ hf.blogInfo.Logo }}" title="{{ hf.blogInfo.Title }}"/>
    				</div>
    				{% endif %}
    				<div>
    				    {% hf.blogInfo.Title | raw %}
    				</div>
				</a>
			</h1>
			<div id="blogDesc">
				{% hf.blogInfo.SubTitle | raw %}
			</div>
		</div>
	</div>

	<!-- Static navbar -->
	<div class="navbar navbar-default">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{{ indexUrl }}">
	      	{% if hf.blogInfo.Logo %}
			    <img src="{{ hf.blogInfo.Logo }}" title="{{ hf.blogInfo.Title }}"/>
			{% endif if %}
			{% hf.blogInfo.Title | raw %}
	      </a>
	    </div>
	    <div class="navbar-collapse collapse">
	      <ul class="nav navbar-nav">

	    	<li class="{% if hf.curIsIndex %}active{% endif %}"><a href="{{ indexUrl }}">主页</a></li>
		    <!-- 分类页 -->
		   	{% for cate in hf.cates %}
				<li class="{% ifequal cate.CateId hf.curCateId %}active{% endifequal %}">
					<a href="{% hf.cateUrl %}/{% single.UrlTitle %}"
					>{% single.Title %} </a>
				</li>
			{% endfor  %}

			<!-- 单页 -->
			{% for single in hf.singles %}
			    <li class="{% ifequal hf.curSingleId single.SingleId %}active{% endifequal %}">
					<a href="{%  hf.singleUrl %}/{% single.UrlTitle %}">{% single.Title %}</a>
				</li>
			{% endfor %}

			<!-- 归档 -->
			<li class="{% if hf.curIsArchive %} active{% endif  %} ">
				<a href="{% hf.archiveUrl %} ">归档</a>
			</li>
			<li class="{% if hf.curIsTags %} active{% endif  %} ">
				<a href="{% hf.tagsUrl %} ">标签</a>
			</li>

	      </ul>
	      <form class="navbar-form navbar-right" id="search" onsubmit="search(event);return false;">
	      	<div class="input-group">
			  	<span class="input-group-addon" id="searchIcon" onclick="search(event);"><i class="fa fa-search"></i></span>
		        <input type="text" placeholder="search" id="searchInput" class="form-control" value="{{ keywords }}">
		  	</div>
	      </form>
	    </div><!--/.nav-collapse -->
	  </div>
	</div>
</div>

blog/templates/blog/highlight.html
<link href="{{$.prettifyCssUrl}}" type="text/css" rel="stylesheet"/>
<script src="{{$.prettifyJsUrl}}"></script>
<script>
$("pre").addClass("prettyprint linenums");
prettyPrint();
</script>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load custom_markdown %}
{% block content %}
<div id="posts">
    {% for article in articles %}
    <div class="each-post">
        <div class="title">
            <a href="http://blog.leanote.com/post/2997215859/8060701fdacd" title="全文">
                {{ article.title }}
            </a>
        </div>
        <div class="created-time">
            <i class="fa fa-bookmark-o"></i>
{#            <a class="label label-default label-post" href="http://blog.leanote.com/tag/2997215859/python">python</a>#}
{#            <a class="label label-default label-post" href="http://blog.leanote.com/tag/2997215859/django">django</a>#}
            {% for tag in article.tags %}
            <a class="label label-default label-post" href="http://blog.leanote.com/tag/2997215859/django">{{ tag }}</a>&nbsp;
            {% endfor %}
            <i class="fa fa-clock-o"></i> {{ article.pub_time | date:"Y-m-d H:i:s" }}
            &nbsp;&nbsp;
            <span class="fa fa-eye"></span> 1 &nbsp;&nbsp;
            <span class="fa fa-thumbs-o-up"></span> 0 &nbsp;&nbsp;
        &nbsp;&nbsp;<span class="fa fa-comments-o"></span> 0 &nbsp;&nbsp;
        </div>
        <div class="desc">
            <div>
                <div id="wmd-preview" class="preview-content"></div>
                <div id="wmd-preview-section-117" class="wmd-preview-section preview-content">
                    <div class="se-section-delimiter"></div>
                    <p>
                    {{ article.content | custom_markdown | truncatechars:500 }}
                    </p>
                </div>
            </div>
        </div>
        <div id="moreContainer">
            <a class="more" href="http://blog.leanote.com/post/2997215859/8060701fdacd" title="全文">查看</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/index2.html
{% include "header.html" %}

<div id="postsContainer">

	<div id="posts">
		{% include "post_abstract.html" %}
		<!-- 分页 -->
		{% include "paging.html" %}
    </div>
</div>
{% include "footer_js.html" %}
{% include "highlight.html" %}

</body>
</html>

blog/templates/blog/paging.html
{{if gt $.paging.TotalPage 1}}

<!-- 上一页 -->
{{if gt $.paging.CurPage 1}}
    {{set . "prePageClass" ""}}
    {{set . "prePageUrl" (urlConcat $.pagingBaseUrl "page" (incr $.paging.CurPage -1)) }}
{{else}}
    {{set . "prePageClass" "disabled"}}
    {{set . "prePageUrl" "#"}}
{{end}}

<!-- 下一页 -->
{{if lt $.paging.CurPage $.paging.TotalPage }}
    {{set . "nextPageClass" ""}}
    {{set . "nextPageUrl" (urlConcat $.pagingBaseUrl "page" (incr $.paging.CurPage 1)) }}
{{else}}
    {{set . "nextPageClass" "disabled"}}
    {{set . "nextPageUrl" "#"}}
{{end}}


<ul class="pager">
	<li class="{{$.prePageClass}}"><a href="{{$.prePageUrl}}">上一页</a></li>
	<li>{{$.paging.CurPage}}/{{$.paging.TotalPage}}</li>
	<li class="{{$.nextPageClass}}"><a href="{{$.nextPageUrl}}">下一页</a></li>
</ul>

{{end}}

blog/templates/blog/post_abstract.html
{{range $.posts}}
	<div class="each-post">
		<div class="title">
			<a href="{{$.postUrl}}/{{.UrlTitle}}" title="全文">
				{{.Title}}
			</a>
		</div>
		<div class="created-time">
			{{if .Tags}} 
			    <i class="fa fa-bookmark-o"></i>
				{{blogTags $ .Tags}}
				&nbsp;&nbsp;
			{{end}}
			
			<i class="fa fa-clock-o"></i> {{.PublicTime | datetime}} 
			&nbsp;&nbsp;
			<span class="fa fa-eye"></span> {{.ReadNum}}
			&nbsp;&nbsp;
			<span class="fa fa-thumbs-o-up"></span> {{.LikeNum}}
			&nbsp;&nbsp;
			<span class="fa fa-comments-o"></span> {{.CommentNum}}
		</div>
		<div class="desc">
			{{.Abstract | raw}}
		</div>
		<div id="moreContainer">
		    <a class="more" href="{{$.postUrl}}/{{.UrlTitle}}" title="全文">查看</a>
        </div>	
	</div>
{{else}}
<div class="each-post">
无
</div>
{{end}}

blog/templates/blog/search.html
{% extends "blog/base.html" %}

{% block content %}
<div class="posts">
    {% if error %}
        <h2 class="post-title">没有相关文章题目</a></h2>
    {% else %}
    {% for article in articles %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url "blog:article_page" article_id=article.id %}">{{ article.title }}</a></h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ article.pub_time |date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="{% url "blog:search_tag" tag_name=article.category %}">{{ article.category }}</a>
                    </p>
            </header>
        </section>
    {% endfor %}
    {% endif %}
</div><!-- /.blog-post -->
{% endblock %}

blog/templates/blog/tag.html
{% extends "blog/base.html" %}

{% load custom_markdown %}
{% block content %}
<div class="posts">
    {% for article in articles %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url "blog:article_page" article_id=article.id %}">{{ article.title }}</a></h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ article.pub_time|date:"Y M d"}}</a> <a class="post-category post-category-js" href="{% url "blog:search_tag" tag_name=article.category %}">{{ article.category|title }}</a>
                    </p>
            </header>

            <div class="post-description">
                <p>
                    {{ article.content|custom_markdown }}
                </p>
            </div>
            <a class="pure-button" href="{% url "blog:article_page" article_id=article.id %}">Read More >>> </a>
        </section>
    {% endfor %}
</div><!-- /.blog-post -->
{% endblock %}